/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import controller.SearchProduct;
import DAO.Daomaytinh;
import java.awt.Desktop;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import model.Account;
import model.Laptop;
import model.MayTinh;
import model.PC;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author Robot
 */
public class ProductForm extends javax.swing.JInternalFrame {

    private DefaultTableModel tblModel;
    DecimalFormat formatter = new DecimalFormat("###,###,###");
    private javax.swing.JButton btnToggleStatus;

    public ProductForm() {
        initComponents();
        initToggleButton();
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        tblSanPham.setDefaultEditor(Object.class, null);
        initTable();
        loadDataToTable();
        changeTextFind();
        jComboBoxLuaChon.addItem("Trạng thái");
    }

    private void initToggleButton() {
        btnToggleStatus = new javax.swing.JButton("Đổi trạng thái");
        btnToggleStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-update-left-rotation-40.png")));
        btnToggleStatus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnToggleStatus.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnToggleStatus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnToggleStatus.setFocusable(false);
        btnToggleStatus.addActionListener(e -> toggleTrangThaiSelect());
        jToolBar1.add(btnToggleStatus);
    }
    
    public void checkRole(Account t) {
        if(t.getRole().equals("Nhân viên nhập") || t.getRole().equals("Nhân viên xuất")) {
            btnAdd.setEnabled(false);
            btnDelete.setEnabled(false);
            btnEdit.setEnabled(false);
            jButton6.setEnabled(false);
            jButton2.setEnabled(false);
            btnToggleStatus.setEnabled(false);
        }
    }

    public final void initTable() {
        tblModel = new DefaultTableModel();
        String[] headerTbl = new String[]{"Mã máy", "Tên máy", "Số lượng", "Đơn giá", "Bộ xử lí", "RAM", "Bộ nhớ", "Loại máy", "Trạng thái"};
        tblModel.setColumnIdentifiers(headerTbl);
        tblSanPham.setModel(tblModel);
        tblSanPham.getColumnModel().getColumn(0).setPreferredWidth(5);
        tblSanPham.getColumnModel().getColumn(1).setPreferredWidth(200);
        tblSanPham.getColumnModel().getColumn(2).setPreferredWidth(5);
        tblSanPham.getColumnModel().getColumn(5).setPreferredWidth(5);
        tblSanPham.getColumnModel().getColumn(6).setPreferredWidth(5);
    }

    /**
     * Tải toàn bộ sản phẩm đang hoạt động (trangThai=1) từ DB vào bảng.
     * Chỉ hiển thị sản phẩm chưa bị xóa mềm.
     */
    public void loadDataToTable() {
        try {
            ArrayList<MayTinh> armt = Daomaytinh.getInstance().selectAll();
            tblModel.setRowCount(0);
            for (MayTinh i : armt) {
                String loaimay = (i instanceof Laptop) ? "Laptop" : "PC/Case";
                String trangThaiStr = (i.getTrangThai() == 1) ? "Đang kinh doanh" : "Ngừng kinh doanh";
                tblModel.addRow(new Object[]{
                    i.getMaMay(), i.getTenMay(), i.getSoLuong(),
                    formatter.format(i.getGia()) + "đ",
                    i.getTenCpu(), i.getRam(), i.getRom(), loaimay, trangThaiStr
                });
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDetail = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButton6 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jComboBoxLuaChon = new javax.swing.JComboBox<>();
        jTextFieldSearch = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSanPham = new javax.swing.JTable();

        setBorder(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setBorder(javax.swing.BorderFactory.createTitledBorder("Chức năng"));
        jToolBar1.setRollover(true);

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_add_40px.png"))); // NOI18N
        btnAdd.setText("Thêm");
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.setFocusable(false);
        btnAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdd.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAdd);

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_delete_40px.png"))); // NOI18N
        btnDelete.setText("Xoá");
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDelete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDelete);

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_edit_40px.png"))); // NOI18N
        btnEdit.setText("Sửa");
        btnEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEdit.setFocusable(false);
        btnEdit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEdit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEdit);

        btnDetail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_eye_40px.png"))); // NOI18N
        btnDetail.setText("Xem chi tiết");
        btnDetail.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDetail.setFocusable(false);
        btnDetail.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDetail.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDetail);
        jToolBar1.add(jSeparator1);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_spreadsheet_file_40px.png"))); // NOI18N
        jButton6.setText("Xuất Excel");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton6);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_xls_40px.png"))); // NOI18N
        jButton2.setText("Nhập Excel");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm kiếm"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBoxLuaChon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Mã máy", "Tên máy", "Số lượng", "Đơn giá", "RAM", "CPU", "Dung lượng", "Card màn hình", "Xuất xứ", "Đã xóa" }));
        jComboBoxLuaChon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxLuaChonActionPerformed(evt);
            }
        });
        jComboBoxLuaChon.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jComboBoxLuaChonPropertyChange(evt);
            }
        });
        jPanel3.add(jComboBoxLuaChon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 150, 40));

        jTextFieldSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldSearchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldSearchKeyReleased(evt);
            }
        });
        jPanel3.add(jTextFieldSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 360, 40));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_reset_25px_1.png"))); // NOI18N
        jButton7.setText("Làm mới");
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, 140, 40));

        tblSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblSanPham);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1168, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed

        AddProduct a = new AddProduct(this, (JFrame) javax.swing.SwingUtilities.getWindowAncestor(this), rootPaneCheckingEnabled);
        a.setVisible(true);

    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        if (tblSanPham.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn sản phẩm cần xoá");
        } else {
            xoaMayTinhSelect();
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        if (tblSanPham.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn sản phẩm cần sửa");
        } else {
            UpdateProduct a = new UpdateProduct(this, (JFrame) javax.swing.SwingUtilities.getWindowAncestor(this), rootPaneCheckingEnabled);
            a.setVisible(true);
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        try {
            JFileChooser jFileChooser = new JFileChooser();
            jFileChooser.showSaveDialog(this);
            File saveFile = jFileChooser.getSelectedFile();
            if (saveFile != null) {
                saveFile = new File(saveFile.toString() + ".xlsx");
                Workbook wb = new XSSFWorkbook();
                Sheet sheet = wb.createSheet("Product");

                Row rowCol = sheet.createRow(0);
                for (int i = 0; i < tblSanPham.getColumnCount(); i++) {
                    Cell cell = rowCol.createCell(i);
                    cell.setCellValue(tblSanPham.getColumnName(i));
                }

                for (int j = 0; j < tblSanPham.getRowCount(); j++) {
                    Row row = sheet.createRow(j + 1);
                    for (int k = 0; k < tblSanPham.getColumnCount(); k++) {
                        Cell cell = row.createCell(k);
                        if (tblSanPham.getValueAt(j, k) != null) {
                            cell.setCellValue(tblSanPham.getValueAt(j, k).toString());
                        }

                    }
                }
                FileOutputStream out = new FileOutputStream(new File(saveFile.toString()));
                wb.write(out);
                wb.close();
                out.close();
                openFile(saveFile.toString());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        File excelFile;
        FileInputStream excelFIS = null;
        BufferedInputStream excelBIS = null;
        XSSFWorkbook excelJTableImport = null;
        ArrayList<MayTinh> listAccExcel = new ArrayList<MayTinh>();
        JFileChooser jf = new JFileChooser();
        int result = jf.showOpenDialog(null);
        jf.setDialogTitle("Open file");
        Workbook workbook = null;
        if (result == JFileChooser.APPROVE_OPTION) {
            try {
                excelFile = jf.getSelectedFile();
                excelFIS = new FileInputStream(excelFile);
                excelBIS = new BufferedInputStream(excelFIS);
                excelJTableImport = new XSSFWorkbook(excelBIS);
                XSSFSheet excelSheet = excelJTableImport.getSheetAt(0);
                for (int row = 1; row <= excelSheet.getLastRowNum(); row++) {
                    XSSFRow excelRow = excelSheet.getRow(row);
                    String maMay = excelRow.getCell(0).getStringCellValue();
                    String tenMay = excelRow.getCell(1).getStringCellValue();
                    int soLuong = (int) excelRow.getCell(2).getNumericCellValue();
                    String giaFomat = excelRow.getCell(3).getStringCellValue().replaceAll(",", "");
                    int viTri = giaFomat.length() - 1;
                    String giaoke = giaFomat.substring(0, viTri) + giaFomat.substring(viTri + 1);
                    double donGia = Double.parseDouble(giaoke);
                    String boXuLi = excelRow.getCell(4).getStringCellValue();
                    String ram = excelRow.getCell(5).getStringCellValue();
                    String boNho = excelRow.getCell(6).getStringCellValue();
                    // Suy loaimay từ prefix mã máy để khớp constructor 11 tham số
                    String loaiMayExcel = maMay.startsWith("LP") ? "Laptop" : "PC";
                    MayTinh mt = new MayTinh(maMay, tenMay, soLuong, donGia, boXuLi, ram, "", "", boNho, 1, loaiMayExcel);
                    listAccExcel.add(mt);
                    DefaultTableModel table_acc = (DefaultTableModel) tblSanPham.getModel();
                    table_acc.setRowCount(0);
                    loadDataToTableSearch(listAccExcel);
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(ProductForm.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(ProductForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        // Lưu từng sản phẩm vào DB, phân loại dựa vào tiền tố mã máy
        // Mã bắt đầu bằng "LP" → Laptop, "PC" → PC/Case
        for (MayTinh mayTinh : listAccExcel) {
            if (mayTinh.getMaMay().startsWith("LP")) {
                // Tạo Laptop với kichThuocMan=0, dungLuongPin="" (Excel không có cột này)
                Laptop lapNew = new Laptop(0, "", mayTinh.getMaMay(), mayTinh.getTenMay(),
                        mayTinh.getSoLuong(), mayTinh.getGia(), mayTinh.getTenCpu(),
                        mayTinh.getRam(), mayTinh.getXuatXu(), mayTinh.getCardManHinh(),
                        mayTinh.getRom(), 1, "Laptop");
                Daomaytinh.getInstance().insert(lapNew);
            } else if (mayTinh.getMaMay().startsWith("PC")) {
                // Tạo PC với mainBoard="", congSuatNguon=0 (Excel không có cột này)
                PC pcNew = new PC("", 0, mayTinh.getMaMay(), mayTinh.getTenMay(),
                        mayTinh.getSoLuong(), mayTinh.getGia(), mayTinh.getTenCpu(),
                        mayTinh.getRam(), mayTinh.getXuatXu(), mayTinh.getCardManHinh(),
                        mayTinh.getRom(), 1, "PC");
                Daomaytinh.getInstance().insert(pcNew);
            } else {
                JOptionPane.showMessageDialog(this, "Mã máy " + mayTinh.getMaMay()
                        + " không hợp lệ! Phải bắt đầu bằng LP (Laptop) hoặc PC.",
                        "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            }
        }
        // Reload bảng sau khi import xong
        loadDataToTable();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        jComboBoxLuaChon.setSelectedIndex(0);
        loadDataToTable();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void btnDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailActionPerformed
        // TODO add your handling code here:
        if (tblSanPham.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn sản phẩm !");
        } else {
            DetailProduct a = new DetailProduct(this, (JFrame) javax.swing.SwingUtilities.getWindowAncestor(this), rootPaneCheckingEnabled);
            a.setVisible(true);
        }
    }//GEN-LAST:event_btnDetailActionPerformed

    private void jTextFieldSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSearchKeyReleased
        // TODO add your handling code here:
        String luaChon = jComboBoxLuaChon.getSelectedItem().toString();
        String content = jTextFieldSearch.getText();
        ArrayList<MayTinh> result = searchFn(luaChon, content);
        loadDataToTableSearch(result);
    }//GEN-LAST:event_jTextFieldSearchKeyReleased

    private void jComboBoxLuaChonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxLuaChonActionPerformed
        // TODO add your handling code here:
        String luaChon = jComboBoxLuaChon.getSelectedItem().toString();
        String content = jTextFieldSearch.getText();
        ArrayList<MayTinh> result = searchFn(luaChon, content);
        loadDataToTableSearch(result);
    }//GEN-LAST:event_jComboBoxLuaChonActionPerformed

    private void jTextFieldSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSearchKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextFieldSearchKeyPressed

    private void jComboBoxLuaChonPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jComboBoxLuaChonPropertyChange
        // TODO add your handling code here:
        String luaChon = jComboBoxLuaChon.getSelectedItem().toString();
        String content = jTextFieldSearch.getText();
        ArrayList<MayTinh> result = searchFn(luaChon, content);
        loadDataToTableSearch(result);
    }//GEN-LAST:event_jComboBoxLuaChonPropertyChange

    /**
     * Gọi SearchProduct.search() để lọc danh sách sản phẩm.
     * Ánh xạ các giá trị ComboBox của form sang field tương ứng trong SearchProduct.
     *
     * @param luaChon giá trị đang chọn trong jComboBoxLuaChon
     * @param content từ khóa tìm kiếm
     * @return danh sách sản phẩm phù hợp
     */
    public ArrayList<MayTinh> searchFn(String luaChon, String content) {
        ArrayList<MayTinh> allProducts = Daomaytinh.getInstance().selectAll();

        // "Đã xóa" = lọc riêng sản phẩm Ngừng kinh doanh (trangThai=0)
        if ("Đã xóa".equals(luaChon)) {
            ArrayList<MayTinh> discontinued = new ArrayList<>();
            for (MayTinh m : allProducts) {
                if (m.getTrangThai() == 0) {
                    discontinued.add(m);
                }
            }
            return SearchProduct.search(discontinued, content, "Tất cả");
        }

        // Lọc theo Trạng thái: so sánh text "Đang kinh doanh" / "Ngừng kinh doanh"
        if ("Trạng thái".equals(luaChon)) {
            ArrayList<MayTinh> filtered = new ArrayList<>();
            for (MayTinh m : allProducts) {
                String trangThaiStr = (m.getTrangThai() == 1) ? "Đang kinh doanh" : "Ngừng kinh doanh";
                if (content.trim().isEmpty() || trangThaiStr.toLowerCase().contains(content.trim().toLowerCase())) {
                    filtered.add(m);
                }
            }
            return filtered;
        }

        // Ánh xạ tên ComboBox sang field cho SearchProduct
        String field;
        switch (luaChon) {
            case "Mã máy":   field = "Mã máy";   break;
            case "Tên máy":  field = "Tên máy";  break;
            case "Loại máy": field = "Loại máy"; break;
            default:         field = "Tất cả";   break;
        }

        return SearchProduct.search(allProducts, content, field);
    }

    /**
     * Kiểm tra sản phẩm đang chọn trong bảng có phải Laptop không.
     * Dùng instanceof vì Daomaytinh.selectById() trả về Laptop/PC instance thực sự.
     *
     * @return true nếu là Laptop, false nếu là PC
     */
    public boolean checklap() {
        return getMayTinhSelect() instanceof Laptop;
    }

    /**
     * Lấy thông tin chi tiết Laptop của sản phẩm đang chọn (có kichThuocMan, dungLuongPin).
     *
     * @return Laptop instance, hoặc null nếu sản phẩm không phải Laptop
     */
    public Laptop getDetailLapTop() {
        MayTinh m = getMayTinhSelect();
        return (m instanceof Laptop) ? (Laptop) m : null;
    }

    /**
     * Lấy thông tin chi tiết PC của sản phẩm đang chọn (có mainBoard, congSuatNguon).
     *
     * @return PC instance, hoặc null nếu sản phẩm không phải PC
     */
    public PC getDetailPC() {
        MayTinh m = getMayTinhSelect();
        return (m instanceof PC) ? (PC) m : null;
    }

    public void xoaMayTinhSelect() {
        if (tblSanPham.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn sản phẩm cần xoá!");
            return;
        }
        MayTinh remove = getMayTinhSelect();
        if (remove.getSoLuong() > 0) {
            JOptionPane.showMessageDialog(this,
                "Không thể xóa! Sản phẩm còn " + remove.getSoLuong() + " cái trong kho.",
                "Lỗi xóa", JOptionPane.WARNING_MESSAGE);
            loadDataToTable();
            return;
        }
        int luaChon = JOptionPane.showConfirmDialog(this, "Bạn có muốn xoá sản phẩm này?",
                "Xoá sản phẩm", JOptionPane.YES_NO_OPTION);
        if (luaChon == JOptionPane.YES_OPTION) {
            int ketqua = Daomaytinh.getInstance().delete(remove);
            if (ketqua > 0) {
                JOptionPane.showMessageDialog(this, "Xóa sản phẩm thành công!");
            } else {
                JOptionPane.showMessageDialog(this, "Không thể xóa! Sản phẩm đang được dùng trong phiếu nhập/xuất.",
                        "Lỗi xóa", JOptionPane.ERROR_MESSAGE);
            }
        }
        loadDataToTable();
    }

    private void toggleTrangThaiSelect() {
        if (tblSanPham.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn sản phẩm cần đổi trạng thái!");
            return;
        }
        MayTinh product = getMayTinhSelect();
        int trangThaiMoi = (product.getTrangThai() == 1) ? 0 : 1;
        String tenTrangThai = (trangThaiMoi == 1) ? "Đang kinh doanh" : "Ngừng kinh doanh";
        int confirm = JOptionPane.showConfirmDialog(this,
            "Đổi trạng thái sản phẩm thành \"" + tenTrangThai + "\"?",
            "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            product.setTrangThai(trangThaiMoi);
            int ketqua = Daomaytinh.getInstance().update(product);
            if (ketqua > 0) {
                JOptionPane.showMessageDialog(this, "Đổi trạng thái thành công!");
            } else {
                JOptionPane.showMessageDialog(this, "Đổi trạng thái thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
        loadDataToTable();
    }

    /**
     * Lấy đối tượng MayTinh (Laptop hoặc PC) tương ứng với dòng đang chọn trong bảng.
     * Dùng maMay ở cột 0 để truy vấn lại DB (đảm bảo có đủ thông tin chi tiết).
     *
     * @return MayTinh (thực ra là Laptop hoặc PC) của dòng đang chọn
     */
    public MayTinh getMayTinhSelect() {
        int i_row = tblSanPham.getSelectedRow();
        String maMay = tblModel.getValueAt(i_row, 0).toString();
        // selectById() trả về Laptop hoặc PC instance tùy loại máy
        return Daomaytinh.getInstance().selectById(maMay);
    }

    /**
     * Đổ danh sách sản phẩm đã lọc vào bảng.
     * Dùng chung cho cả tìm kiếm và kết quả import Excel.
     *
     * @param result danh sách sản phẩm cần hiển thị
     */
    public void loadDataToTableSearch(ArrayList<MayTinh> result) {
        try {
            tblModel.setRowCount(0);
            for (MayTinh i : result) {
                String loaimay = (i instanceof Laptop) ? "Laptop" : "PC/Case";
                String trangThaiStr = (i.getTrangThai() == 1) ? "Đang kinh doanh" : "Ngừng kinh doanh";
                tblModel.addRow(new Object[]{
                    i.getMaMay(), i.getTenMay(), i.getSoLuong(),
                    formatter.format(i.getGia()) + "đ",
                    i.getTenCpu(), i.getRam(), i.getRom(), loaimay, trangThaiStr
                });
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void changeTextFind() {
        jTextFieldSearch.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {

            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                /* do nothing */
                if (jTextFieldSearch.getText().length() == 0) {
                    loadDataToTable();
                }
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                /* do nothing */

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDetail;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBoxLuaChon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JTextField jTextFieldSearch;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tblSanPham;
    // End of variables declaration//GEN-END:variables

    private void openFile(String file) {
        try {
            File path = new File(file);
            Desktop.getDesktop().open(path);
        } catch (IOException e) {
            System.out.println(e);
        }
    }
}
